export const LOGIN_USER = 'LOGIN_USER'; 
export const LOGOUT_USER = 'LOGOUT_USER'; 

export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_DATE = 'UPDATE_DATE';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const ADD_ATTENDEE = 'ADD_ATTENDEE';
export const DELETE_ATTENDEE = 'DELETE_ATTENDEE';
export const UPDATE_MEETING = 'UPDATE_MEETING';
export const SAVE_UPDATED_MEETING = 'SAVE_UPDATED_MEETING';
export const SCHEDULE_MEETING = 'SCHEDULE_MEETING';
export const RESET_MEETING = 'RESET_MEETING';